### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by wip-abramson** [austintgriffith/scaffold-eth#105]
Hey, 

Tried to get this working after the Eth Denver talk today - sounds like a really cool project.

Ran into a weird issue on yarn start:

Config:
Node 12.13.1
Yarn 1.21.1

Error error Couldn't find match for "36040d5b5312f19a025782b5e36663823494c2f3" then a bunch of output.
Ends with
 at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at Git.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:51440:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Any ideas?

Cheers

**Comment by wip-abramson** [comment]
Not entirely sure what the issue was, something messed up with my Yarn I think. Sorted it now!

**Comment by hobbydev71** [comment]
> Not entirely sure what the issue was, something messed up with my Yarn I think. Sorted it now!

Hi @wip-abramson ,
I have same issue now.
How did you solve that?
