### ISSUE TITLE
Module not found: @walletconnect/client 

### ISSUE THREAD

**Issue by iafhurtado** [austintgriffith/scaffold-eth#159]
`C:/Users/jaibo/scaffold-eth/.yarn/cache/@walletconnect-client-npm-1.3.1-6d57d78cd3-3e4d93b9eb.zip/node_modules/@walletconnect/client/dist/cjs/index.js
Module not found: @walletconnect/client tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

This makes my yarn start to fail at compiling, any ideas on how I can fix this?
Thanks in advance

**Comment by iafhurtado** [comment]
I also tried installing and starting other scaffold projects such as the aave-apeand nifty-ink but it also fails at starting the yarn, even though now I get this internal error message, any idea what could be causing this? Incompatible yarn version?
```
Internal Error: @uniswap-v1-app/monorepo@workspace:.: This package doesn't seem to be present in your lockfile; try to make an install to update your resolutions
    at J.getCandidates (C:\Users\jaibo\.yarn\releases\yarn-berry.cjs:2:348376)
    at n.getCandidates (C:\Users\jaibo\.yarn\releases\yarn-berry.cjs:2:337366)
    at C:\Users\jaibo\.yarn\releases\yarn-berry.cjs:2:359022
    at Module.w (C:\Users\jaibo\.yarn\releases\yarn-berry.cjs:2:418493)
    at C (C:\Users\jaibo\.yarn\releases\yarn-berry.cjs:2:358985)
```
