### ISSUE TITLE
serverless-auth branch - Error: npm.cmd ls -prod -json -depth=1 failed with code 1

### ISSUE THREAD

**Issue by EsteFilipe** [austintgriffith/scaffold-eth#354]
Running on Windows 10, I get the following error when running the command `npx serverless deploy`  to deploy the serverless API:

`Error: npm.cmd ls -prod -json -depth=1 failed with code 1`

Full output:

```
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - JWT_SECRET
Serverless:      - SLS_DEBUG
Serverless:      - JWT_EXPIRATION_TIME
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Invoke webpack:validate
undefined 2
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Starting type checking service...
Serverless: Invoke webpack:package

 Error ---------------------------------------------------

  Error: npm.cmd ls -prod -json -depth=1 failed with code 1
      at ChildProcess.<anonymous> (C:\git_projects\eth-auth\packages\api\node_modules\serverless-webpack\lib\utils.js:91:16)
      at ChildProcess.emit (events.js:315:20)
      at ChildProcess.EventEmitter.emit (domain.js:467:12)
      at maybeClose (internal/child_process.js:1048:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              14.15.5
     Framework Version:         2.52.1 (local)
     Plugin Version:            5.4.3
     SDK Version:               4.2.6
     Components Version:        3.14.2
```

Seems to be a problem with the plugin `serverless-webpack`.

Similar error here for reference:
https://github.com/serverless-heaven/serverless-webpack/issues/690

**Comment by EsteFilipe** [comment]
Found a quick fix, despite not using yarn.

Removed the workspace parameter from package.json in the `api` package, such that this is the new file:

{
  "name": "scaffold-eth-api",
  "version": "0.1.0",
  "description": "A TypeScript starter for Serverless Framework",
  "main": "handler.js",
  "private": true,
  "scripts": {
    "lint": "npx eslint src/**/*.ts",
    "lint:fix": "npm run lint -- --fix",
    "test": "serverless-bundle test",
    "deploy": "serverless deploy --stage dev"
  },
  "author": "",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/AnomalyInnovations/serverless-typescript-starter.git"
  },
  "devDependencies": {
    "@types/aws-lambda": "^8.10.64",
    "@types/jest": "^26.0.14",
    "eslint": "^7.5.0",
    "serverless": "^2.34.0",
    "serverless-bundle": "4.0.1",
    "serverless-domain-manager": "^5.1.0",
    "serverless-dotenv-plugin": "^3.0.0",
    "serverless-iam-roles-per-function": "3.1.0",
    "serverless-offline": "^6.8.0"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "3.11.0",
    "@aws-sdk/s3-request-presigner": "3.11.0",
    "ethers": "^5.0.17",
    "ipfs-only-hash": "4.0.0",
    "jsonwebtoken": "^8.5.1",
    "mailparser": "^2.3.4",
    "mime-types": "2.1.30",
    "uuidv4": "6.2.7"
  }
}

Ran `npm install`. Then downgraded serverless-webpack to v5.3.5 using `npm i serverless-webpack@5.3.5 --save-dev`.

`npx serverless deploy` works after this.

**Comment by codenamejason** [comment]
Glad you found a fix, any ideas on a long term solution?

**Comment by EsteFilipe** [comment]
@codenamejason currently short in time finishing a project using this branch for a hackathon, towards the end when I polish off the edges I'll try to find something permanent.

**Comment by EsteFilipe** [comment]
I didn't find a way to install using yarn while avoiding the error. Tried multiple versions of `serverless-webpack` but always got the same error.

The best workaround I've found was to remove the /api package from the yarn workspaces and do the dependencies install for that package separately using `npm install`.

For that I had to specify each package I wanted to use `yarn` for dependencies installation in the root package.json, instead of using the wildcard "packages/*"

You can see what I did here:
https://github.com/EsteFilipe/discord-ethereum-authentication

But either way, the root problem of this is using webpack for packaging code to deploy into a lambda - I'm not sure if this is good practice by itself. But I'm also not sure if it's possible to do a Typescript deployment without doing it.
