### ISSUE TITLE
yarn run chain: address already in use 127.0.0.1:8545

### ISSUE THREAD

**Issue by oren** [austintgriffith/scaffold-eth#54]
```
yarn run chain

yarn run v1.22.5
$ yarn workspace @scaffold-eth/buidler chain
$ buidler node
Error: listen EADDRINUSE: address already in use 127.0.0.1:8545
    at Server.setupListenHandle [as _listen2] (net.js:1228:14)
    at listenInCluster (net.js:1276:12)
    at GetAddrInfoReqWrap.doListen (net.js:1415:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/oren/.nvm/versions/node/v12.8.0/bin/node
Arguments: /usr/share/yarn/lib/cli.js chain
Directory: /tmp/test/scaffold-eth/packages/buidler
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

More info:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

---

```
$ uname -a
Linux oren 4.4.0-179-generic #209-Ubuntu SMP Fri Apr 24 17:48:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by sylar217** [comment]
The error means that some other process is already listening on port 8545. I see two ways to fix this:
- Kill the process using port 8545 if not needed or configure that to use a different port.
- Configure buidler chain to use a different port.

**Comment by azf20** [comment]
yes - buidler (now renamed hardhat) runs on 8545 by default, so will throw if you're running something else on that already. You might have another local chain running already? @sylar217's suggestions would both work, though the second would then require some scaffold-eth reconfiguration (as the react app expects 8545). Closing, but ping again if it's a live issue!
